import './bg.scss';
export function AnimatedBackground() {
  return (
    <div className='stars'>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
      <div className='star'></div>
    </div>
  );
}
